#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mohib
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Abdullah_DB")]
	public partial class MhddbmlDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertMed(Med instance);
    partial void UpdateMed(Med instance);
    partial void DeleteMed(Med instance);
    partial void InsertMed1(Med1 instance);
    partial void UpdateMed1(Med1 instance);
    partial void DeleteMed1(Med1 instance);
    partial void InsertMeds_user(Meds_user instance);
    partial void UpdateMeds_user(Meds_user instance);
    partial void DeleteMeds_user(Meds_user instance);
    partial void InsertPt(Pt instance);
    partial void UpdatePt(Pt instance);
    partial void DeletePt(Pt instance);
    partial void InsertPt_Md_Bill(Pt_Md_Bill instance);
    partial void UpdatePt_Md_Bill(Pt_Md_Bill instance);
    partial void DeletePt_Md_Bill(Pt_Md_Bill instance);
    partial void InsertTotal1(Total1 instance);
    partial void UpdateTotal1(Total1 instance);
    partial void DeleteTotal1(Total1 instance);
    partial void InsertTotal(Total instance);
    partial void UpdateTotal(Total instance);
    partial void DeleteTotal(Total instance);
    #endregion
		
		public MhddbmlDataContext() : 
				base(global::Mohib.Properties.Settings.Default.Abdullah_DBConnectionString1, mappingSource)
		{
			OnCreated();
		}
		
		public MhddbmlDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MhddbmlDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MhddbmlDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public MhddbmlDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Med> Meds
		{
			get
			{
				return this.GetTable<Med>();
			}
		}
		
		public System.Data.Linq.Table<Med1> Med1s
		{
			get
			{
				return this.GetTable<Med1>();
			}
		}
		
		public System.Data.Linq.Table<Meds_user> Meds_users
		{
			get
			{
				return this.GetTable<Meds_user>();
			}
		}
		
		public System.Data.Linq.Table<Pt> Pts
		{
			get
			{
				return this.GetTable<Pt>();
			}
		}
		
		public System.Data.Linq.Table<Pt_Md_Bill> Pt_Md_Bills
		{
			get
			{
				return this.GetTable<Pt_Md_Bill>();
			}
		}
		
		public System.Data.Linq.Table<Total1> Total1s
		{
			get
			{
				return this.GetTable<Total1>();
			}
		}
		
		public System.Data.Linq.Table<Total> Totals
		{
			get
			{
				return this.GetTable<Total>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Med")]
	public partial class Med : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Med_Name;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<int> _Qnt;
		
		private System.Nullable<long> _Prf;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMed_NameChanging(string value);
    partial void OnMed_NameChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnQntChanging(System.Nullable<int> value);
    partial void OnQntChanged();
    partial void OnPrfChanging(System.Nullable<long> value);
    partial void OnPrfChanged();
    #endregion
		
		public Med()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Med_Name", DbType="VarChar(50)")]
		public string Med_Name
		{
			get
			{
				return this._Med_Name;
			}
			set
			{
				if ((this._Med_Name != value))
				{
					this.OnMed_NameChanging(value);
					this.SendPropertyChanging();
					this._Med_Name = value;
					this.SendPropertyChanged("Med_Name");
					this.OnMed_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qnt", DbType="Int")]
		public System.Nullable<int> Qnt
		{
			get
			{
				return this._Qnt;
			}
			set
			{
				if ((this._Qnt != value))
				{
					this.OnQntChanging(value);
					this.SendPropertyChanging();
					this._Qnt = value;
					this.SendPropertyChanged("Qnt");
					this.OnQntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prf", DbType="BigInt")]
		public System.Nullable<long> Prf
		{
			get
			{
				return this._Prf;
			}
			set
			{
				if ((this._Prf != value))
				{
					this.OnPrfChanging(value);
					this.SendPropertyChanging();
					this._Prf = value;
					this.SendPropertyChanged("Prf");
					this.OnPrfChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Meds")]
	public partial class Med1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _Med_Name;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<int> _Qnt;
		
		private System.Nullable<long> _Prf;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnMed_NameChanging(string value);
    partial void OnMed_NameChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnQntChanging(System.Nullable<int> value);
    partial void OnQntChanged();
    partial void OnPrfChanging(System.Nullable<long> value);
    partial void OnPrfChanged();
    #endregion
		
		public Med1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Med_Name", DbType="VarChar(50)")]
		public string Med_Name
		{
			get
			{
				return this._Med_Name;
			}
			set
			{
				if ((this._Med_Name != value))
				{
					this.OnMed_NameChanging(value);
					this.SendPropertyChanging();
					this._Med_Name = value;
					this.SendPropertyChanged("Med_Name");
					this.OnMed_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Qnt", DbType="Int")]
		public System.Nullable<int> Qnt
		{
			get
			{
				return this._Qnt;
			}
			set
			{
				if ((this._Qnt != value))
				{
					this.OnQntChanging(value);
					this.SendPropertyChanging();
					this._Qnt = value;
					this.SendPropertyChanged("Qnt");
					this.OnQntChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Prf", DbType="BigInt")]
		public System.Nullable<long> Prf
		{
			get
			{
				return this._Prf;
			}
			set
			{
				if ((this._Prf != value))
				{
					this.OnPrfChanging(value);
					this.SendPropertyChanging();
					this._Prf = value;
					this.SendPropertyChanged("Prf");
					this.OnPrfChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Meds_user")]
	public partial class Meds_user : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private string _UName;
		
		private string _Med_Name;
		
		private System.Nullable<int> _price;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnUNameChanging(string value);
    partial void OnUNameChanged();
    partial void OnMed_NameChanging(string value);
    partial void OnMed_NameChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    #endregion
		
		public Meds_user()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_UName", DbType="VarChar(50)")]
		public string UName
		{
			get
			{
				return this._UName;
			}
			set
			{
				if ((this._UName != value))
				{
					this.OnUNameChanging(value);
					this.SendPropertyChanging();
					this._UName = value;
					this.SendPropertyChanged("UName");
					this.OnUNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Med_Name", DbType="VarChar(50)")]
		public string Med_Name
		{
			get
			{
				return this._Med_Name;
			}
			set
			{
				if ((this._Med_Name != value))
				{
					this.OnMed_NameChanging(value);
					this.SendPropertyChanging();
					this._Med_Name = value;
					this.SendPropertyChanged("Med_Name");
					this.OnMed_NameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pt")]
	public partial class Pt : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _phone;
		
		private string _FName;
		
		private string _Pre;
		
		private string _DR;
		
		private string _Madicin;
		
		private string _Date_PT;
		
		private string _issue;
		
		private System.Nullable<int> _price;
		
		private System.Nullable<long> _Phone2nd;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnphoneChanging(long value);
    partial void OnphoneChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnPreChanging(string value);
    partial void OnPreChanged();
    partial void OnDRChanging(string value);
    partial void OnDRChanged();
    partial void OnMadicinChanging(string value);
    partial void OnMadicinChanged();
    partial void OnDate_PTChanging(string value);
    partial void OnDate_PTChanged();
    partial void OnissueChanging(string value);
    partial void OnissueChanged();
    partial void OnpriceChanging(System.Nullable<int> value);
    partial void OnpriceChanged();
    partial void OnPhone2ndChanging(System.Nullable<long> value);
    partial void OnPhone2ndChanged();
    #endregion
		
		public Pt()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="VarChar(50)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Pre", DbType="VarChar(500)")]
		public string Pre
		{
			get
			{
				return this._Pre;
			}
			set
			{
				if ((this._Pre != value))
				{
					this.OnPreChanging(value);
					this.SendPropertyChanging();
					this._Pre = value;
					this.SendPropertyChanged("Pre");
					this.OnPreChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_DR", DbType="VarChar(50)")]
		public string DR
		{
			get
			{
				return this._DR;
			}
			set
			{
				if ((this._DR != value))
				{
					this.OnDRChanging(value);
					this.SendPropertyChanging();
					this._DR = value;
					this.SendPropertyChanged("DR");
					this.OnDRChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madicin", DbType="VarChar(50)")]
		public string Madicin
		{
			get
			{
				return this._Madicin;
			}
			set
			{
				if ((this._Madicin != value))
				{
					this.OnMadicinChanging(value);
					this.SendPropertyChanging();
					this._Madicin = value;
					this.SendPropertyChanged("Madicin");
					this.OnMadicinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Date_PT", DbType="VarChar(50)")]
		public string Date_PT
		{
			get
			{
				return this._Date_PT;
			}
			set
			{
				if ((this._Date_PT != value))
				{
					this.OnDate_PTChanging(value);
					this.SendPropertyChanging();
					this._Date_PT = value;
					this.SendPropertyChanged("Date_PT");
					this.OnDate_PTChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_issue", DbType="VarChar(50)")]
		public string issue
		{
			get
			{
				return this._issue;
			}
			set
			{
				if ((this._issue != value))
				{
					this.OnissueChanging(value);
					this.SendPropertyChanging();
					this._issue = value;
					this.SendPropertyChanged("issue");
					this.OnissueChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_price", DbType="Int")]
		public System.Nullable<int> price
		{
			get
			{
				return this._price;
			}
			set
			{
				if ((this._price != value))
				{
					this.OnpriceChanging(value);
					this.SendPropertyChanging();
					this._price = value;
					this.SendPropertyChanged("price");
					this.OnpriceChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Phone2nd", DbType="BigInt")]
		public System.Nullable<long> Phone2nd
		{
			get
			{
				return this._Phone2nd;
			}
			set
			{
				if ((this._Phone2nd != value))
				{
					this.OnPhone2ndChanging(value);
					this.SendPropertyChanging();
					this._Phone2nd = value;
					this.SendPropertyChanged("Phone2nd");
					this.OnPhone2ndChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Pt_Md_Bill")]
	public partial class Pt_Md_Bill : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private long _phone;
		
		private string _FName;
		
		private string _Madicin;
		
		private System.Nullable<int> _total;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnphoneChanging(long value);
    partial void OnphoneChanged();
    partial void OnFNameChanging(string value);
    partial void OnFNameChanged();
    partial void OnMadicinChanging(string value);
    partial void OnMadicinChanged();
    partial void OntotalChanging(System.Nullable<int> value);
    partial void OntotalChanged();
    #endregion
		
		public Pt_Md_Bill()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_phone", DbType="BigInt NOT NULL", IsPrimaryKey=true)]
		public long phone
		{
			get
			{
				return this._phone;
			}
			set
			{
				if ((this._phone != value))
				{
					this.OnphoneChanging(value);
					this.SendPropertyChanging();
					this._phone = value;
					this.SendPropertyChanged("phone");
					this.OnphoneChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_FName", DbType="VarChar(50)")]
		public string FName
		{
			get
			{
				return this._FName;
			}
			set
			{
				if ((this._FName != value))
				{
					this.OnFNameChanging(value);
					this.SendPropertyChanging();
					this._FName = value;
					this.SendPropertyChanged("FName");
					this.OnFNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Madicin", DbType="VarChar(50)")]
		public string Madicin
		{
			get
			{
				return this._Madicin;
			}
			set
			{
				if ((this._Madicin != value))
				{
					this.OnMadicinChanging(value);
					this.SendPropertyChanging();
					this._Madicin = value;
					this.SendPropertyChanged("Madicin");
					this.OnMadicinChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_total", DbType="Int")]
		public System.Nullable<int> total
		{
			get
			{
				return this._total;
			}
			set
			{
				if ((this._total != value))
				{
					this.OntotalChanging(value);
					this.SendPropertyChanging();
					this._total = value;
					this.SendPropertyChanged("total");
					this.OntotalChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Total1")]
	public partial class Total1 : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _id;
		
		private System.Nullable<long> _Inc_Med;
		
		private System.Nullable<long> _Dr_fees;
		
		private string _Datee;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnidChanging(int value);
    partial void OnidChanged();
    partial void OnInc_MedChanging(System.Nullable<long> value);
    partial void OnInc_MedChanged();
    partial void OnDr_feesChanging(System.Nullable<long> value);
    partial void OnDr_feesChanged();
    partial void OnDateeChanging(string value);
    partial void OnDateeChanged();
    #endregion
		
		public Total1()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_id", DbType="Int NOT NULL", IsPrimaryKey=true)]
		public int id
		{
			get
			{
				return this._id;
			}
			set
			{
				if ((this._id != value))
				{
					this.OnidChanging(value);
					this.SendPropertyChanging();
					this._id = value;
					this.SendPropertyChanged("id");
					this.OnidChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inc_Med", DbType="BigInt")]
		public System.Nullable<long> Inc_Med
		{
			get
			{
				return this._Inc_Med;
			}
			set
			{
				if ((this._Inc_Med != value))
				{
					this.OnInc_MedChanging(value);
					this.SendPropertyChanging();
					this._Inc_Med = value;
					this.SendPropertyChanged("Inc_Med");
					this.OnInc_MedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr_fees", DbType="BigInt")]
		public System.Nullable<long> Dr_fees
		{
			get
			{
				return this._Dr_fees;
			}
			set
			{
				if ((this._Dr_fees != value))
				{
					this.OnDr_feesChanging(value);
					this.SendPropertyChanging();
					this._Dr_fees = value;
					this.SendPropertyChanged("Dr_fees");
					this.OnDr_feesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datee", DbType="VarChar(50)")]
		public string Datee
		{
			get
			{
				return this._Datee;
			}
			set
			{
				if ((this._Datee != value))
				{
					this.OnDateeChanging(value);
					this.SendPropertyChanging();
					this._Datee = value;
					this.SendPropertyChanged("Datee");
					this.OnDateeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Total")]
	public partial class Total : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private System.Nullable<long> _Inc_Med;
		
		private System.Nullable<long> _Dr_fees;
		
		private string _Datee;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnInc_MedChanging(System.Nullable<long> value);
    partial void OnInc_MedChanged();
    partial void OnDr_feesChanging(System.Nullable<long> value);
    partial void OnDr_feesChanged();
    partial void OnDateeChanging(string value);
    partial void OnDateeChanged();
    #endregion
		
		public Total()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Inc_Med", DbType="BigInt", IsPrimaryKey=true)]
		public System.Nullable<long> Inc_Med
		{
			get
			{
				return this._Inc_Med;
			}
			set
			{
				if ((this._Inc_Med != value))
				{
					this.OnInc_MedChanging(value);
					this.SendPropertyChanging();
					this._Inc_Med = value;
					this.SendPropertyChanged("Inc_Med");
					this.OnInc_MedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Dr_fees", DbType="BigInt")]
		public System.Nullable<long> Dr_fees
		{
			get
			{
				return this._Dr_fees;
			}
			set
			{
				if ((this._Dr_fees != value))
				{
					this.OnDr_feesChanging(value);
					this.SendPropertyChanging();
					this._Dr_fees = value;
					this.SendPropertyChanged("Dr_fees");
					this.OnDr_feesChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Datee", DbType="VarChar(50)")]
		public string Datee
		{
			get
			{
				return this._Datee;
			}
			set
			{
				if ((this._Datee != value))
				{
					this.OnDateeChanging(value);
					this.SendPropertyChanging();
					this._Datee = value;
					this.SendPropertyChanged("Datee");
					this.OnDateeChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
